######################################################################
# Automatically generated by qmake (3.1) Fri May 26 15:57:31 2017
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = qt_calculator
INCLUDEPATH += .

# Input
HEADERS += calculator.h
SOURCES += calculator.cpp main.cpp
